---

- name: install drupal
  apt: name=drupal7 state=installed

- name: register drupal module with apache
  command: cp /etc/drupal/7/apache2.conf /etc/apache2/mods-enabled/drupal.conf

# src=/etc/drupal/7/apache2.conf dest=/etc/apache2/mods-enabled/drupal.conf
